# .streamlit/secrets.toml

ENDPOINT="ubdatabase-1.c77gabmjroih.us-east-1.rds.amazonaws.com"
PORT=3306
USER="admin"
REGION="us-east-1"
DBNAME="ub_skincare"
PASSWORD="Ubskincare"
aws_access_key_id="AKIATCOF5TJFRDJXH2MH"
aws_secret_access_key="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"
